/** FAQ Diva Mabruro — 8 pertanyaan inti, jawaban ringkas di kalimat pertama (ramah SEO/GEO). */
export const FAQS = [
  { q: "Apa itu Haji Khusus?", a: "Haji Khusus (Haji Plus) adalah program haji resmi dengan kuota tersendiri yang masa tunggunya jauh lebih singkat serta layanan dan fasilitasnya lebih nyaman dibanding haji reguler. Program ini diselenggarakan travel berizin seperti Diva Mabruro." },
  { q: "Berapa setoran awal dan total DP porsi?", a: "Total DP untuk memproses porsi adalah USD 5.000 — terdiri dari setoran awal USD 1.000 dan sisa DP USD 4.000 yang dapat dicicil 12–60 bulan. Porsi diproses setelah syarat dan DP terpenuhi sesuai ketentuan resmi." },
  { q: "Apakah Rp1,2 juta per bulan adalah harga penuh Haji?", a: "Bukan. Rp1,2 juta per bulan adalah simulasi cicilan sisa DP USD 4.000 selama 60 bulan dengan asumsi kurs Rp18.000/USD (4.000 × 18.000 = Rp72.000.000 ÷ 60). Biaya program Haji Khusus dihitung terpisah, mulai USD 13.400 per orang." },
  { q: "Berapa perkiraan masa tunggu Haji Khusus?", a: "Estimasi 5–9 tahun, jauh lebih singkat dibanding haji reguler yang dapat mencapai 25–40 tahun. Angka aktual mengikuti nomor porsi, kuota, dan kebijakan tahun berjalan." },
  { q: "Apakah Diva Mabruro travel resmi?", a: "Ya. Diva Mabruro terdaftar resmi di Kementerian Agama RI sebagai Penyelenggara Perjalanan Ibadah Umrah (PPIU) No. 25 Tahun 2019 dan No. 874 Tahun 2020, serta tercatat aktif sebagai provider Penyelenggara Ibadah Haji Khusus (PIHK). Bukti legalitas dapat diminta tertulis sebelum Anda membayar apa pun." },
  { q: "Pembayaran dilakukan ke rekening siapa?", a: "Seluruh pembayaran hanya masuk ke rekening resmi atas nama perusahaan (PT Diva Mabruro) — bukan rekening pribadi. Anda menerima bukti pendaftaran tertulis, dan kantor kami di Sidoarjo & Surabaya dapat dikunjungi langsung." },
  { q: "Apakah program ini cocok untuk orang tua?", a: "Sangat cocok. Fasilitas dan pendampingan Diva dirancang membantu jamaah lanjut usia beribadah lebih tenang — dari pengurusan dokumen, manasik, handling keberangkatan, hingga pendampingan muthawif di Tanah Suci." },
  { q: "Bagaimana proses konsultasi dan pendaftarannya?", a: "Mulai dari konsultasi gratis via WhatsApp (tanpa kewajiban mendaftar), lalu setoran awal USD 1.000 ke rekening perusahaan, cicilan sisa DP sesuai tenor pilihan, pengurusan dokumen, manasik, hingga keberangkatan. Seluruh proses dapat dilakukan jarak jauh tanpa harus datang ke kantor." },
];
